const VER_POPUP = "VER_POPUP";
const CERRAR_POPUP = "CERRAR_POPUP";
const USER_LOGGED = "USER_LOGGED";
const USER_LOGOUT = "USER_LOGOUT";

export { VER_POPUP, CERRAR_POPUP, USER_LOGGED, USER_LOGOUT };
